### ISSUE TITLE
Getting some strange x

### ISSUE THREAD

**Issue by navteniev** [CSC59939/Rails#59]
When trying to create an account I get some random error message.

<img width="457" alt="screen shot 2018-11-14 at 7 40 19 pm" src="https://user-images.githubusercontent.com/619960/48522161-9382a400-e845-11e8-8c4d-a0ce23c3fd8b.png">

**Comment by ayushyamitabh** [comment]
@navteniev thank you for bringing this to our attention, look to be missing proper error validation. this will be fixed by next iteration

@khelif96 @LiuYuHao @hetobias @edwin0108 @whuang001 Please make sure to have proper error messages across the whole website. I will fix this particular issue

**Comment by edwin0108** [comment]
This issue has been resolved along with the password validation functionality update.
