### ISSUE TITLE
A lot of Columbia Colleges

### ISSUE THREAD

**Issue by buenoluis007** [CSC59939/Rails#61]
Whenever I type to join Columbia College, what should I choose?!?!

![image](https://user-images.githubusercontent.com/33500965/48522233-dfcde400-e845-11e8-8786-558dd92c4b98.png)

**Comment by ayushyamitabh** [comment]
@buenoluis007 thank you for bringing this to our attention, seems to be a duplicate of #70 we'll be tracking the progress for this bug on that issue - please look to that issue to check for any progress on this bug.

closing this issue.

**Comment by edwin0108** [comment]
Resolved in #73 
Closing.
