### ISSUE TITLE
Wont update classes based on college.

### ISSUE THREAD

**Issue by buenoluis007** [CSC59939/Rails#69]
When you select a college (ie: CUNY City College), and when you change the college, it doesn't update classes selected from the other college. Thus it hangs on requesting the class.

![image](https://user-images.githubusercontent.com/33500965/48522565-27a13b00-e847-11e8-9a79-82466fa37ca2.png)

**Comment by ayushyamitabh** [comment]
@edwin0108 `this.state.classList` needs to be emptied when selected university changes. Also, try to fix class dropdown styling to contain all class data.

let me know what branch this was worked on and i'll help.

**Comment by edwin0108** [comment]
@ayushyamitabh this is within the join class branch, we'll discuss that tomorrow for sure.

**Comment by ayushyamitabh** [comment]
This has been addressed in #73 - awaiting review

**Comment by ayushyamitabh** [comment]
Resolved in #73 .
Closing.
