### ISSUE TITLE
join University issue

### ISSUE THREAD

**Issue by EvanVasquez** [CSC59939/Rails#70]
When filling in your university, it displays the same university multiple times.
![join search](https://user-images.githubusercontent.com/32246279/48522750-dc3b5c80-e847-11e8-88d3-a87068727e3f.JPG)

**Comment by ayushyamitabh** [comment]
@edwin0108 check the implementation for the API here, does the array of universities get emptied at each search? Or is this the College Scorecard API fault?

**Comment by edwin0108** [comment]
@ayushyamitabh that should be the API problem because I tried multiple college search before testing and when I check the console the array is refreshed, we'll discuss that in tomorrow's meeting.

**Comment by ayushyamitabh** [comment]
This has been addressed in #73 - awaiting review

**Comment by ayushyamitabh** [comment]
Resolved in #73 .
Closing.
